---
title: "Intro to Markdown"
output: html_notebook
---

Markdown is a way of formating or styling text from plain form to HTML. You can use to write reproducible, dynamic reports that combine text, images and code. These reports can be then exported as pdf, doc or html files.

****

Compare the formating in markdown and compare with the result generated in the viewer pane of Rstudio:

Plain text   

End a line with two spaces to start a new paragraph.   

*italics* and _italics_   

**bold** and __bold__   

superscript^2^   

~~strikethrough~~   

[Hyperlink](http://eb.mpg.de/)   

# Header 1   
## Header 2  
### Header 3   
#### Header 4   
##### Header 5   
###### Header 6   

endash: --   
emdash: ---   
ellipsis: ...   

horizontal rule (or slide break):  

****

> block quote

* unordered list 
* item 2     
    + sub-item 1     
    + sub-item 2 

1. ordered list 
1. item 2 
    1. sub-item 1     
    1. sub-item 2 
  
| Column 1 | Column 2 | Column 3 |
|----------|----------|----------|
|  One | 1 | A |
| Two | 2 | B |
| Three | 3 | C |


`inline code` can be inserted with backticks

```
# code block
print '3 backticks'
```

****

Take ~10 to 15 minutes to go through [this markdown interactive tutorial](https://commonmark.org/help/tutorial/). Once you are finished, go ahead and format the following text. Try to include all the elements of markdown styling you can.

# Max Planck Institute for Developmental Biology

## Research
The variety of topics investigated by scientists at the MPI for Developmental Biology is extensive, although all subjects have a biological theme. The cutting-edge technology in molecular and cellular biology and computational science available at the institute is enabling scientists to gain increasing insight into cellular and developmental processes. A highly dynamic and interdisciplinary approach is applied from the molecular level to cells, tissues, and the whole organism. [Read more](http://eb.mpg.de/research/)

## Departments of the MPI for Developmental Biology

* **Department 1** - *Protein Evolution*
* **Department 2** - *Biochemistry*
* **Department 3** - *Microbiome Science*
* **Department 4** - *Evolutionary Biology*
* **Department 5** - *Cell Biology*
* **Department 6** - *Molecular Biology*

## Facilities
The core facilities of the MPI for Developmental Biology are:

1. Electron Microscopy
1. Light Microscopy
1. NMR Spectroscopy
1. Genome Center
1. X-Ray Crystallography.

The facilities offer a broad range of methods and techniques and provide a motivating and helpful environment where researchers/users are trained and supported throughout their projects.

## Events
Every other year the institutes of the Tübingen campus invite the general public to their **Open House** or participate in the **TÜFF** (*Tübinger Fenster für Forschung*), a science fair. Scientists participate regularly at events like the „Kinder-Uni“ (*Children's University*), the **Maus-Türöffner-Tag** (open house event for children), as well as in presentations and podium discussions hosted by the MPI for Developmental Biology, FML or the partner institutes. 